# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nrfmicro_13" ]
# shield: [ "square68_left", "square68_right" ]
# include:
#   - board: nrfmicro_13
#     shield: square68_left
#   - board: nrfmicro_13
#     shield: square68_right
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: square68_left_with_logging
#
---
include:
  - board: nrfmicro_13
    shield: yyz04_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: yyz04_right
  - board: nice_nano_v2
    shield: settings_reset
    
